# Análise da Composição do Universo de Investimento e Portfólios
Este notebook realiza a análise da composição do universo de ativos utilizado para construção dos portfólios, separando:
1. Ações (Stocks)
2. Não-Ações (ETFs, Closed-End Funds, REITs, etc.)

Todas as visualizações são apresentadas em formato tabular (Tabelas com gradiente de cor para facilitar a leitura), mostrando sempre duas visões:
- **Percentual por Quantidade de Ativos (Count %)**
- **Percentual por Market Cap (Mcap %)**

In [31]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from IPython.display import display

# Função auxiliar para exibir tabelas com estilo
def display_styled_table(df, title):
    print(f"\n--- {title} ---")
    styled_df = (df.style
                 .format("{:.2f}%")
                 .background_gradient(cmap='Blues', axis=1))
    display(styled_df)

## 1. Carregamento e Preparação dos Dados

In [32]:
df_hcm = pd.read_parquet("../../data/07_portfolios_metadata/complete_metadata_hcm.parquet")
df_pozzi = pd.read_parquet("../../data/07_portfolios_metadata/complete_metadata_pozzi.parquet")

print(f"Shape HCM: {df_hcm.shape}")
print(f"Shape Pozzi: {df_pozzi.shape}")

# Extraindo Market Cap baseado no ano de cada linha
def extract_mcap(df):
    def get_mcap(row):
        year = int(row['year'])
        col = f'mcap_{year}'
        if col in row.index:
            return row[col]
        return np.nan
    df['mcap'] = df.apply(get_mcap, axis=1)
    return df

df_hcm = extract_mcap(df_hcm)
df_pozzi = extract_mcap(df_pozzi)

Shape HCM: (40662, 38)
Shape Pozzi: (40662, 38)

In [34]:
# --- CORREÇÃO DE OUTLIER ---
# Copiando os dados corretos de Market Cap da BRK-B para a BRK-A
for df in [df_hcm, df_pozzi]:
    brk_b_mcaps = df[df['Ticker'] == 'BRK-B'].set_index('year')['mcap']
    
    def fix_brka(row):
        if row['Ticker'] == 'BRK-A' and row['year'] in brk_b_mcaps.index:
            return brk_b_mcaps.loc[row['year']]
        return row['mcap']
        
    df['mcap'] = df.apply(fix_brka, axis=1)
# ---------------------------

## 2. Classificação: Ações vs Não-Ações (ETFs, CEFs, REITs)

In [35]:
def classify_asset_type(row):
    industry = str(row['Industry']).lower()
    sector = str(row['Sector']).lower()
    
    if 'exchange traded fund' in industry or 'etf' in industry:
        return 'ETF'
    elif 'closed-end fund' in industry:
        return 'Closed-End Fund'
    elif 'reit' in industry or 'reit' in sector:
        return 'REIT'
    elif 'mutual fund' in industry or 'fund' in industry:
        return 'Other Fund'
    else:
        return 'Stock'

for df in [df_hcm, df_pozzi]:
    df['Asset_Class'] = df.apply(classify_asset_type, axis=1)
    df['Main_Type'] = df['Asset_Class'].apply(lambda x: 'Stock' if x == 'Stock' else 'Non-Stock')

unique_tickers = df_hcm["Ticker"].unique()
df_hcm_unique = df_hcm.iloc[:len(unique_tickers)]

print("Distribuição Global de Tipos de Ativos (Contagem):")
display(pd.DataFrame(df_hcm_unique['Asset_Class'].value_counts()))

Distribuição Global de Tipos de Ativos (Contagem):

                 count
Asset_Class
Stock             3186
ETF               1053
Closed-End Fund    472
REIT               183

In [36]:
len(unique_tickers)

4894

## 3. Análise da Composição do Universo Ano a Ano

In [37]:
def analyze_composition(df, group_col, columns_col):
    # Por Quantidade
    count_df = df.groupby([group_col, columns_col]).size().unstack(fill_value=0)
    count_pct = count_df.div(count_df.sum(axis=1), axis=0) * 100
    
    # Por Market Cap
    mcap_df = df.groupby([group_col, columns_col])['mcap'].sum().unstack(fill_value=0)
    # Evitar divisão por zero caso mcap seja 0
    mcap_pct = mcap_df.div(mcap_df.sum(axis=1).replace(0, np.nan), axis=0) * 100
    
    return count_pct.fillna(0), mcap_pct.fillna(0)

# 3.1 Ações vs Não-Ações
count_pct, mcap_pct = analyze_composition(df_hcm, 'year', 'Main_Type')
display_styled_table(count_pct, "Proporção de Ações vs Não-Ações por ANO (Percentual de QUANTIDADE)")
display_styled_table(mcap_pct, "Proporção de Ações vs Não-Ações por ANO (Percentual de MARKET CAP)")

--- Proporção de Ações vs Não-Ações por ANO (Percentual de QUANTIDADE) ---

--- Proporção de Ações vs Não-Ações por ANO (Percentual de MARKET CAP) ---

### 3.2 Composição Detalhada dos Não-Ações

In [38]:
non_stocks = df_hcm[df_hcm['Main_Type'] == 'Non-Stock']
count_pct, mcap_pct = analyze_composition(non_stocks, 'year', 'Asset_Class')

display_styled_table(count_pct, "Tipos de Não-Ações por ANO (Percentual de QUANTIDADE)")
display_styled_table(mcap_pct, "Tipos de Não-Ações por ANO (Percentual de MARKET CAP)")

--- Tipos de Não-Ações por ANO (Percentual de QUANTIDADE) ---

--- Tipos de Não-Ações por ANO (Percentual de MARKET CAP) ---

### 3.3 Composição do Universo de Ações por Setor

In [39]:
stocks = df_hcm[df_hcm['Main_Type'] == 'Stock']
count_pct, mcap_pct = analyze_composition(stocks, 'year', 'Sector')

display_styled_table(count_pct, "Ações por Setor e ANO (Percentual de QUANTIDADE)")
display_styled_table(mcap_pct, "Ações por Setor e ANO (Percentual de MARKET CAP)")

--- Ações por Setor e ANO (Percentual de QUANTIDADE) ---

--- Ações por Setor e ANO (Percentual de MARKET CAP) ---

### 3.4 Indústria por setores mais representados

In [54]:
# 1. Obtém os setores já ordenados do mais representado para o menos representado no histórico
sectors = stocks['Sector'].value_counts().index

for sector in sectors:
    sector_df = stocks[stocks["Sector"] == sector].copy()
    
    if sector_df.empty:
        continue
        
    # 2. Encontra as 5 indústrias mais representadas no setor (já vem na ordem decrescente)
    top_5_industries = sector_df['Industry'].value_counts().nlargest(5).index
    
    # 3. Cria a nova coluna onde o que não é Top 5 vira 'Others'
    sector_df['Industry_Grouped'] = sector_df['Industry'].apply(
        lambda x: x if x in top_5_industries else 'Others'
    )
    
    # 4. Executa a análise de proporção
    count_pct, mcap_pct = analyze_composition(sector_df, 'year', 'Industry_Grouped')
    
    # 5. Define a ordem desejada das colunas (Top 5 na ordem de tamanho + 'Others' no final)
    col_order = [ind for ind in top_5_industries if ind in count_pct.columns]
    if 'Others' in count_pct.columns:
        col_order.append('Others')
        
    # Aplica a ordenação das colunas nas duas tabelas
    count_pct = count_pct[col_order]
    mcap_pct = mcap_pct[col_order]
    
    # 6. Exibe as tabelas
    display_styled_table(
        count_pct, 
        f"Ações por Indústria e ANO (Setor: {sector}) - Percentual de QUANTIDADE"
    )
    
    display_styled_table(
        mcap_pct, 
        f"Ações por Indústria e ANO (Setor: {sector}) - Percentual de MARKET CAP"
    )

--- Ações por Indústria e ANO (Setor: Financial) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Financial) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Industrials) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Industrials) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Healthcare) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Healthcare) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Technology) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Technology) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Consumer Cyclical) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Consumer Cyclical) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Energy) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Energy) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Consumer Defensive) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Consumer Defensive) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Basic Materials) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Basic Materials) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Communication Services) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Communication Services) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Utilities) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Utilities) - Percentual de MARKET CAP ---

--- Ações por Indústria e ANO (Setor: Real Estate) - Percentual de QUANTIDADE ---

--- Ações por Indústria e ANO (Setor: Real Estate) - Percentual de MARKET CAP ---

In [48]:
fin_sector = stocks[stocks["Sector"]=="Financial"]

count_pct, mcap_pct = analyze_composition(fin_sector, 'year', 'Industry')

display_styled_table(count_pct, "Ações por Indústria e ANO (Setor Financials) (Percentual de QUANTIDADE)")
display_styled_table(mcap_pct, "Ações por Setor e ANO (Setor Financials) (Percentual de MARKET CAP)")

--- Ações por Indústria e ANO (Setor Financials) (Percentual de QUANTIDADE) ---

--- Ações por Setor e ANO (Setor Financials) (Percentual de MARKET CAP) ---

## 4. Comparação: Decil 1 (Central) vs Decil 10 (Periférico)

In [40]:
def extract_decile_analysis(df):
    df['decile_num'] = df['portfolio'].str.extract(r'(\d+)').astype(float)
    max_decile_val = int(df['decile_num'].max())
    max_decile_str = f'decil_{max_decile_val}'
    
    d1 = df[df['portfolio'] == 'decil_1'].copy()
    d10 = df[df['portfolio'] == max_decile_str].copy()
    
    d1['Grupo'] = 'Decil 1 (Central)'
    d10['Grupo'] = f'Decil {max_decile_val} (Periférico)'
    
    return pd.concat([d1, d10])

df_hcm_comp = extract_decile_analysis(df_hcm)
df_pozzi_comp = extract_decile_analysis(df_pozzi)

### 4.1 HCM: Decil Central vs Periférico - Tipo de Ativo

In [41]:
def display_decile_comparison(df_comp, metric_name):
    # Agregar por Ano, Grupo e Classe de Ativo
    count_df = df_comp.groupby(['year', 'Grupo', 'Asset_Class']).size().unstack(fill_value=0)
    count_pct = count_df.div(count_df.sum(axis=1), axis=0) * 100
    
    mcap_df = df_comp.groupby(['year', 'Grupo', 'Asset_Class'])['mcap'].sum().unstack(fill_value=0)
    mcap_pct = mcap_df.div(mcap_df.sum(axis=1).replace(0, np.nan), axis=0) * 100
    
    display_styled_table(count_pct.fillna(0), f"{metric_name} - Composição de Ativos (Percentual de QUANTIDADE)")
    display_styled_table(mcap_pct.fillna(0), f"{metric_name} - Composição de Ativos (Percentual de MARKET CAP)")

display_decile_comparison(df_hcm_comp, "HCM")

--- HCM - Composição de Ativos (Percentual de QUANTIDADE) ---

--- HCM - Composição de Ativos (Percentual de MARKET CAP) ---

### 4.2 Pozzi: Decil Central vs Periférico - Tipo de Ativo

In [42]:
display_decile_comparison(df_pozzi_comp, "Pozzi")

--- Pozzi - Composição de Ativos (Percentual de QUANTIDADE) ---

--- Pozzi - Composição de Ativos (Percentual de MARKET CAP) ---

### 4.3 Composição Setorial das Ações (Decil 1 vs Decil Periférico)

In [43]:
def display_sector_comparison(df_comp, metric_name):
    stocks_only = df_comp[df_comp['Main_Type'] == 'Stock']
    
    count_df = stocks_only.groupby(['year', 'Grupo', 'Sector']).size().unstack(fill_value=0)
    count_pct = count_df.div(count_df.sum(axis=1), axis=0) * 100
    
    mcap_df = stocks_only.groupby(['year', 'Grupo', 'Sector'])['mcap'].sum().unstack(fill_value=0)
    mcap_pct = mcap_df.div(mcap_df.sum(axis=1).replace(0, np.nan), axis=0) * 100
    
    display_styled_table(count_pct.fillna(0), f"{metric_name} - Setores das Ações (Percentual de QUANTIDADE)")
    display_styled_table(mcap_pct.fillna(0), f"{metric_name} - Setores das Ações (Percentual de MARKET CAP)")

display_sector_comparison(df_hcm_comp, "HCM")
display_sector_comparison(df_pozzi_comp, "Pozzi")

--- HCM - Setores das Ações (Percentual de QUANTIDADE) ---

--- HCM - Setores das Ações (Percentual de MARKET CAP) ---

--- Pozzi - Setores das Ações (Percentual de QUANTIDADE) ---

--- Pozzi - Setores das Ações (Percentual de MARKET CAP) ---

### Composição industrial das ações

In [60]:
def display_top5_industries_ranking(df_comp, metric_name):
    # Função interna para pegar o Top 5 formatado
    def get_top_5(year, decil):
        # AQUI FOI CORRIGIDO: usando 'portfolio' e passando o nome exato do decil
        sub_df = df_comp[(df_comp['year'] == str(year)) & 
                         (df_comp['portfolio'] == decil) & 
                         (df_comp['Main_Type'] == 'Stock')]
        
        result = []
        if not sub_df.empty:
            # Pegamos os 5 mais presentes e transformamos em % 
            top5 = sub_df['Industry'].value_counts(normalize=True).head(5)
            result = [f"{nome} ({val*100:.1f}%)" for nome, val in top5.items()]
            
        while len(result) < 5:
            result.append("-")
            
        return result

    years = sorted(df_comp['year'].dropna().unique())
    d1_data, d10_data = [], []
    
    # Processa ano a ano apontando para 'decil_1' e 'decil_10'
    for y in years:
        d1_data.append([y] + get_top_5(y, 'decil_1'))
        d10_data.append([y] + get_top_5(y, 'decil_10'))
        
    cols = ['Year', 'Top 1', 'Top 2', 'Top 3', 'Top 4', 'Top 5']
    d1_df = pd.DataFrame(d1_data, columns=cols).set_index('Year')
    d10_df = pd.DataFrame(d10_data, columns=cols).set_index('Year')
    
    # Exibe as duas tabelas
    print(f"\n{'='*60}\n {metric_name} - NÚCLEO (DECIL 1) - TOP 5 INDÚSTRIAS\n{'='*60}")
    display(d1_df)
    
    print(f"\n{'='*60}\n {metric_name} - PERIFERIA (DECIL 10) - TOP 5 INDÚSTRIAS\n{'='*60}")
    display(d10_df)

# Basta chamar para as duas métricas (usando df_hcm e df_pozzi diretamente):
display_top5_industries_ranking(df_hcm, "HCM")
display_top5_industries_ranking(df_pozzi, "POZZI")

============================================================
 HCM - NÚCLEO (DECIL 1) - TOP 5 INDÚSTRIAS
============================================================

,Top 1,Top 2,Top 3,Top 4,Top 5
Year,,,,,
2014,Banks - Regional (15.1%),Specialty Industrial Machinery (6.3%),Specialty Chemicals (4.4%),Engineering & Construction (3.9%),Electronic Components (3.4%)
2015,Banks - Regional (20.6%),Software - Application (6.1%),Engineering & Construction (4.2%),Auto Parts (3.3%),Building Products & Equipment (2.8%)
2016,Banks - Regional (18.6%),Specialty Industrial Machinery (5.2%),Software - Application (4.6%),Asset Management (4.1%),Aerospace & Defense (4.1%)
2017,Specialty Industrial Machinery (7.3%),Asset Management (5.7%),Software - Infrastructure (5.7%),Banks - Regional (4.9%),Auto Parts (4.9%)
2018,Banks - Regional (20.1%),Specialty Industrial Machinery (5.3%),Engineering & Construction (4.3%),Aerospace & Defense (3.8%),Specialty Chemicals (3.8%)
2019,Banks - Regional (35.1%),Specialty Industrial Machinery (7.8%),Engineering & Construction (3.7%),Credit Services (2.9%),Metal Fabrication (2.9%)
2020,Specialty Industrial Machinery (9.3%),Asset Management (6.0%),Banks - Regional (6.0%),Building Products & Equipment (4.0%),Steel (3.3%)
2021,Banks - Regional (8.2%),Specialty Industrial Machinery (7.1%),Asset Management (5.3%),Specialty Chemicals (4.1%),Aerospace & Defense (3.5%)
2022,Specialty Industrial Machinery (9.7%),Asset Management (7.8%),Specialty Chemicals (7.1%),Banks - Regional (5.8%),Building Products & Equipment (5.2%)
2023,Specialty Industrial Machinery (9.7%),Asset Management (6.1%),Specialty Chemicals (5.5%),Tools & Accessories (4.2%),Building Products & Equipment (4.2%)
2024,Specialty Industrial Machinery (6.8%),Asset Management (5.5%),Software - Infrastructure (4.1%),Electronic Components (3.6%),Banks - Regional (3.6%)

============================================================
 HCM - PERIFERIA (DECIL 10) - TOP 5 INDÚSTRIAS
============================================================

,Top 1,Top 2,Top 3,Top 4,Top 5
Year,,,,,
2014,Banks - Regional (26.6%),Biotechnology (8.1%),Semiconductors (8.1%),Oil & Gas E&P (4.0%),Gold (3.2%)
2015,Banks - Regional (23.0%),Utilities - Regulated Electric (7.7%),Biotechnology (7.7%),Gold (3.1%),Medical Devices (2.6%)
2016,Banks - Regional (18.3%),Utilities - Regulated Electric (10.4%),Biotechnology (4.9%),Asset Management (3.7%),Capital Markets (3.0%)
2017,Banks - Regional (19.3%),Utilities - Regulated Electric (15.2%),Biotechnology (5.5%),Capital Markets (3.4%),Real Estate Services (2.8%)
2018,Utilities - Regulated Electric (16.4%),Banks - Regional (13.2%),Biotechnology (9.2%),Software - Application (5.3%),Oil & Gas E&P (3.3%)
2019,Utilities - Regulated Electric (15.8%),Biotechnology (10.2%),Banks - Regional (10.2%),Capital Markets (5.6%),Asset Management (3.4%)
2020,Asset Management (12.0%),Banks - Regional (8.9%),Biotechnology (6.3%),Software - Application (3.8%),Software - Infrastructure (3.2%)
2021,Asset Management (10.6%),Restaurants (7.6%),Banks - Regional (7.1%),Oil & Gas E&P (5.3%),Software - Application (4.1%)
2022,Biotechnology (34.0%),Asset Management (11.7%),Drug Manufacturers - Specialty & Generic (3.7%),Banks - Regional (3.7%),Packaged Foods (3.2%)
2023,Biotechnology (53.4%),Drug Manufacturers - Specialty & Generic (6.8%),Oil & Gas E&P (4.3%),Capital Markets (3.4%),Medical Devices (3.4%)
2024,Biotechnology (8.9%),Capital Markets (7.4%),Gold (5.3%),Packaged Foods (4.2%),Software - Application (4.2%)

============================================================
 POZZI - NÚCLEO (DECIL 1) - TOP 5 INDÚSTRIAS
============================================================

,Top 1,Top 2,Top 3,Top 4,Top 5
Year,,,,,
2014,Asset Management (5.6%),Diagnostics & Research (4.9%),Aerospace & Defense (4.9%),Packaged Foods (4.2%),Healthcare Plans (4.2%)
2015,Banks - Regional (12.6%),Insurance - Property & Casualty (11.9%),Asset Management (10.4%),Financial Data & Stock Exchanges (4.4%),Capital Markets (4.4%)
2016,Oil & Gas E&P (11.5%),Oil & Gas Equipment & Services (8.3%),Banks - Regional (7.4%),Specialty Chemicals (4.1%),Oil & Gas Midstream (4.1%)
2017,Oil & Gas Equipment & Services (8.4%),Oil & Gas E&P (7.3%),Asset Management (5.2%),Oil & Gas Midstream (4.2%),Chemicals (3.7%)
2018,Oil & Gas E&P (6.6%),Asset Management (5.2%),Oil & Gas Equipment & Services (5.2%),Oil & Gas Midstream (3.9%),Specialty Chemicals (3.9%)
2019,Banks - Regional (8.3%),Insurance - Property & Casualty (6.2%),Trucking (5.5%),Specialty Chemicals (5.5%),Asset Management (4.8%)
2020,Banks - Regional (10.4%),Asset Management (5.8%),Insurance - Property & Casualty (5.4%),Aerospace & Defense (5.0%),Capital Markets (5.0%)
2021,Banks - Regional (8.8%),Insurance - Property & Casualty (7.5%),Oil & Gas E&P (5.7%),Capital Markets (5.3%),Aerospace & Defense (4.4%)
2022,Credit Services (7.0%),Capital Markets (7.0%),Diagnostics & Research (6.4%),Insurance - Property & Casualty (5.2%),Drug Manufacturers - General (4.7%)
2023,Aerospace & Defense (6.6%),Specialty Industrial Machinery (5.1%),Credit Services (4.0%),Engineering & Construction (2.9%),Electronic Components (2.9%)
2024,Medical Devices (6.2%),Biotechnology (4.6%),Communication Equipment (4.1%),Diagnostics & Research (4.1%),Drug Manufacturers - Specialty & Generic (3.6%)

============================================================
 POZZI - PERIFERIA (DECIL 10) - TOP 5 INDÚSTRIAS
============================================================

,Top 1,Top 2,Top 3,Top 4,Top 5
Year,,,,,
2014,Banks - Regional (15.5%),Semiconductors (11.3%),Oil & Gas E&P (8.2%),Gold (7.2%),Biotechnology (6.2%)
2015,Biotechnology (20.6%),Banks - Regional (15.0%),Gold (3.7%),Healthcare Plans (2.8%),Diagnostics & Research (2.8%)
2016,Banks - Regional (18.9%),Trucking (3.4%),Medical Instruments & Supplies (3.0%),Residential Construction (3.0%),Biotechnology (3.0%)
2017,Banks - Regional (15.4%),Utilities - Regulated Electric (13.6%),Biotechnology (9.3%),Software - Application (3.7%),Medical Devices (3.1%)
2018,Biotechnology (25.2%),Semiconductors (10.7%),Semiconductor Equipment & Materials (6.1%),Drug Manufacturers - Specialty & Generic (5.3%),Banks - Regional (4.2%)
2019,Biotechnology (11.0%),Banks - Regional (10.3%),Apparel Retail (5.1%),Specialty Retail (4.8%),Software - Application (4.0%)
2020,Asset Management (13.6%),Banks - Regional (7.3%),Biotechnology (5.1%),Credit Services (3.4%),Airlines (3.4%)
2021,Restaurants (9.8%),Asset Management (8.4%),Banks - Regional (5.6%),Software - Application (4.2%),Travel Services (4.2%)
2022,Biotechnology (50.8%),Asset Management (8.4%),Drug Manufacturers - Specialty & Generic (4.7%),Restaurants (3.7%),Medical Devices (2.7%)
2023,Biotechnology (51.1%),Drug Manufacturers - Specialty & Generic (5.9%),Software - Infrastructure (5.3%),Medical Devices (5.1%),Software - Application (5.1%)
2024,Utilities - Regulated Electric (16.3%),Oil & Gas Equipment & Services (13.6%),Capital Markets (7.1%),Gold (6.0%),Utilities - Regulated Gas (5.4%)